import 'package:flutter/material.dart';

Color kMainColor = Color(0xFF27b7da);
Color kDisabledColor = Color(0xff616161);
Color kCompleatColor = Color(0xff90EE90);
Color kTextColor = Color(0xfffff9e9);
Color kWhiteColor = Colors.white;
Color kLightTextColor = Color(0xff747474);
Color kCardBackgroundColor = Color(0xfff8f9fd);
Color kTransparentColor = Colors.transparent;
Color kMainTextColor = Color(0xff000000);
Color kIconColor = Color(0xffc4c8c1);
Color kHintColor = Color(0xffa3a3a3);
Color kContainerTextColor = Color(0xff606060);
Color kButtonColor = Color(0xfffafafa);
Color kButtonBorderColor = Color(0xffe1e1e1);
Color kButtonTextColor = Color(0xffbababa);
Color kContainerShadowColor = Color(0xff87fddc82);
Color kLighterTextColor = Color(0xffFFFFFF);
Color inProcessColor = Color(0xffF1BC23);
Color starColor = Colors.amber;
Color textFieldColor = Color(0xff7c7c7c);
Color lightGreyColor = Color(0xffacacac);
Color black2 = Color(0xff4d4d4d);
