name: healthcrad_user
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.21+21

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.15
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^7.0.0
  flutter_datetime_picker: ^1.5.1
  fluttertoast: ^8.0.9
  animation_wrappers: 0.0.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3
  razorpay_flutter:
  lottie: ^2.2.0
  geocoding: ^2.0.5
  image_picker: any
  dio: ^4.0.6
  flutter_pdfview: ^1.2.2
  path_provider: ^2.0.10
  file_picker:
  flutter_openmoney:
  flutter_sms: ^2.3.3
  permission_handler: ^9.2.0
  http: ^0.13.4
  path: ^1.8.0
  flutter_google_places_hoc081098: ^1.2.0
  google_api_headers: ^1.5.0+1
  google_maps_webservice: ^0.0.19
  flutter_tawk:
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  syncfusion_flutter_datepicker: ^19.3.59
  polymaker: ^1.0.3
  geolocator: ^8.0.5
  table_calendar:
  intl:
  flutter_file_downloader: ^1.1.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:

  image_path: "assets/ixon.png"
  android: true
  ios: true



flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf


  assets:
    - assets/
    - assets/CategoryImages/
    - assets/HomeBanner/
    - assets/banners/
    - assets/Categories/
    - assets/DoctorCategory/
    - assets/HomeBanner/
    - assets/Icons/
    - assets/Medicines/
    - assets/SellerImages/
    - assets/FooterIcons/
    - assets/ProfilePics/
    - assets/PaymentIcons/
    - assets/Doctors/